{% set version = "0.3.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-log4r
  version: {{ version|replace("-", "_") }}

source:
  fn: log4r_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/log4r_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/log4r/log4r_{{ version }}.tar.gz

  sha256: 8e5d0221298410e48bee9d9a983a23e1834ce88592f9d931471bfdb05f37a691

build:
  noarch: generic
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('log4r')"  # [not win]
    - "\"%R%\" -e \"library('log4r')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/log4r/index.html
  license: Artistic-2.0
  summary: logr4 provides an object-oriented logging system that uses an API roughly equivalent
    to log4j and its related variants.
  license_family: OTHER
extra:
   recipe-maintainers:
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
