travis:
  secure:
    BINSTAR_TOKEN: G9cPop+xNz2JkFvJz6M+OijDivw11kWZTS2kUTtaslBSENcplzAKQ5j+PPp0iDOWyr9UvLILF67iM22lfbNE6KaNp8pqS4DPKWzPNTUVK5oIJr9GMaMmyQUZbNL25iJgfZuiEI4emNxDxT0JJXc210JAJ47AkNfKGgD5R1DhyfNPxMpRTHkYsFKTFA5zMHGPioO6bJ/E9uoKze6U4pDZhQ+qj19BXhaxcSmAZFL8T7PPQOacVxWWRjeP5UECYo4viO8nx0JR2ILLQd1gBi0qR16ypu+9qGG/jg/YTr7gWr0MIUXDXEql35vf749+HOquiOwtFGrcOnHtUAWVq6dyJY39+FGRJdf/nZlVIooOz9CFUqBOJQXR+gsdjr1J2cH9ViPwBAYouXCfJHkoSW4EpW2kzSsgS8bdjlEoFxv+M2WH66m8SCVCItMtOmsS/lqoZugKs3ulxUGA/1H4I2zIPJafxw799rARZzlsGhdL/wFlqzA7kUVeaNdLL9N9EJxetj0NmPA2DGMNOaLEzqrnV7/4zM7CH3IVzcRKyt8yuBM5k0yKv+erZd7UtOITjlCpvHmIbLGb1eJtCu4WjCSeeVpBwUp1EqHI0bhd9CifmqPvVx8kmAQ/HXhWp7bEV8IsI1k2Bmk8vTm3Swn/0a6/HQUYFC22BreVtDJu48lUKfk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
