appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: LJkqwxHCHSa6h8CDnpV6Al1vaEv2sfGuWjjWltiAbQ5Us2v0MqpOsspXl68rBYNxavA9/3ZI4mu+Lx/v0GyTa7BbM+1lqqRBTGeBfRgkylto38bXT1zClGz39EXR3a338H7wM7LDHDg936tRtsTfGnHSDgKx+yIzCL1QRV9nRQhdUq3K4yEZipu6VwvifTvohh8jzMCFp5Rs72l+ZNT2ctl7p7ZaXxIssveslKefo/VVXqqoQtHWmt72jBndjUuRwNt764Lr1KVG8lA8tYYYNhLiPZ8qO6Wm6K4KF65DMxT+9hQf2DdDCDs8pno930lePet8Q0i/wQTu0EX8YU9w1sW77s6NK3btDXTL38skQva/tPYBSewUNIqVchlEWxn2Cgt76Z3mGIT8HLi7c8gQEVZoV1YUSILGqbb1xQNEqMuzGwjQrHqy31N3CRqma2CkWGXOS8eJfBMcUrx3SKva98s4tJOd/Pb/i+C55qYQ+w8yjGi427EWgQtO22l71xfGr0p4bbEZiGpm5Jr66GEng7kXT989NBSXC37KfNDGaU5a7PdE/VbX50PWuj163OwY/v160gwlY9fL9IIbR4x5aV3oAce7JnGyba9K+RkVt8BEjG8C+tkGPeXLcRY1rFC9gw1s0Sw7HOKip/aSa+Dk2wt32+xna6sW8adpmv9ITNk=
conda_forge_output_validation: true
